---

- name: setup_put_getxattr
  type: setup
  tmpdirs:
    - name: 014_put_getxattr_builtin
      varname: config_dir
  randnames:
    - test_volume
    - test_rg
    - put_ug
    - cat_ug
  vars:
    - name: local_file
      value: $config_dir/local_file
    - name: syndicate_conf
      value: $config_dir/syndicate.conf
    - name: rg_driver
      value: $SYNDICATE_PYTHON_ROOT/syndicate/rg/drivers/disk
    - name: rg_path
      value: $SYNDICATE_RG_ROOT/syndicate-rg
    - name: put_path
      value: $SYNDICATE_UG_ROOT/syndicate-put
    - name: cat_path
      value: $SYNDICATE_UG_ROOT/syndicate-cat
    - name: getxattr_path
      value: $SYNDICATE_UG_ROOT/syndicate-getxattr
    - name: cached_blocks
      value: '\n1111\n'
  debug: off

- name: config
  type: sequential
  tasks:
    - name: make local_file
      command: $tasksf_dir/mkpatternfile.py $local_file 16384 abcdef

    - name: setup
      command: $SYNDICATE_TOOL --trust_public_key -c "$syndicate_conf" --debug setup "$SYNDICATE_ADMIN" "$SYNDICATE_PRIVKEY_PATH" "$SYNDICATE_MS"

    - name: add test volume
      command: $SYNDICATE_TOOL -c "$syndicate_conf" create_volume name=$test_volume description="test volume" blocksize=4096 email=$SYNDICATE_ADMIN

    - name: create RG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" create_gateway name=$test_rg type=RG volume=$test_volume email=$SYNDICATE_ADMIN private_key=auto port=31111

    - name: update RG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" update_gateway name=$test_rg caps=ALL port=31112 driver=$rg_driver

- name: daemon RG
  type: daemon
  tasks:
    - name: start RG
      command: $rg_path -c "$syndicate_conf" -d2 -f -u $SYNDICATE_ADMIN -v $test_volume -g $test_rg
      exit: 0

- name: setup UGs
  type: sequential
  tasks:
    - name: create put UG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" create_gateway name=$put_ug type=UG volume=$test_volume email=$SYNDICATE_ADMIN private_key=auto port=31111

    - name: update put UG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" update_gateway name=$put_ug caps=ALL

    - name: create cat UG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" create_gateway name=$cat_ug type=UG volume=$test_volume email=$SYNDICATE_ADMIN private_key=auto port=31111

    - name: update cat UG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" update_gateway name=$cat_ug caps=ALL

- name: run put/cat tests
  type: sequential
  tasks:
    - name: test put
      command: $put_path -d2 -f -c "$syndicate_conf" -u $SYNDICATE_ADMIN -v $test_volume -g $put_ug $local_file /put-getxattr

    - name: test cat
      command: $cat_path -d2 -f -c "$syndicate_conf" -u $SYNDICATE_ADMIN -v $test_volume -g $cat_ug /put-getxattr

    - name: getxattr
      command: $getxattr_path -d2 -f -c "$syndicate_conf" -u $SYNDICATE_ADMIN -v $test_volume -g $cat_ug /put-getxattr user.syndicate_cached_blocks
      containsout: $cached_blocks
