---

- name: setup_rename_08
  type: setup
  tmpdirs:
    - name: 178_rename_08_fs
      varname: config_dir
    - name: 178_rename_08_fs_mount
      varname: mount_dir
      mode: 0755
  randnames:
    - test_volume
    - test_rg
    - test_ug
    - test_n0
    - test_n1
    - test_n2
  vars:
    - name: n0
      value: $mount_dir/$test_n0
    - name: n1
      value: $mount_dir/$test_n1
    - name: n2
      value: $mount_dir/$test_n2
    - name: syndicate_conf
      value: $config_dir/syndicate.conf
    - name: rg_driver
      value: $SYNDICATE_PYTHON_ROOT/syndicate/rg/drivers/disk
    - name: rg_path
      value: $SYNDICATE_RG_ROOT/syndicate-rg
    - name: ug_path
      value: $SYNDICATE_UG_ROOT/syndicatefs

- name: config
  type: sequential
  tasks:
    - name: setup
      command: $SYNDICATE_TOOL --trust_public_key -c "$syndicate_conf" --debug setup "$SYNDICATE_ADMIN" "$SYNDICATE_PRIVKEY_PATH" "$SYNDICATE_MS"

    - name: add test volume
      command: $SYNDICATE_TOOL -c "$syndicate_conf" create_volume name=$test_volume description="test volume" blocksize=4096 email=$SYNDICATE_ADMIN

    - name: create RG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" create_gateway name=$test_rg type=RG volume=$test_volume email=$SYNDICATE_ADMIN private_key=auto port=31111

    - name: update RG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" update_gateway name=$test_rg caps=ALL port=31112 driver=$rg_driver

    - name: create UG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" create_gateway name=$test_ug type=UG volume=$test_volume email=$SYNDICATE_ADMIN private_key=auto port=31111

    - name: update UG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" update_gateway name=$test_ug caps=ALL

- name: daemon UG/RG
  type: daemon
  tasks:
    - name: start RG
      command: $rg_path -c "$syndicate_conf" -d2 -f -u $SYNDICATE_ADMIN -v $test_volume -g $test_rg
      exit: 0

    - name: start UG
      command: $ug_path -c "$syndicate_conf" -d2 -f -u $SYNDICATE_ADMIN -v $test_volume -g $test_ug $mount_dir
      exit: 0

- name: check syndicate is mounted
  type: sequential
  tasks:
    - name: wait for syndicatefs to be mounted
      command: sleep 5s

    - name: test filesystem type
      command: stat -f -L -c %T $mount_dir
      compareout: "fuseblk"

- name: run rename tests 08
  type: sequential
  tasks:
    # expect 0 symlink ${n0} ${n1}
    - name: T1 - expect 0 symlink [n0] [n1]
      command: fstest symlink ${n0} ${n1}
      compareout: "0"

    # expect 0 symlink ${n1} ${n0}
    - name: T1 - expect 0 symlink [n1] [n0]
      command: fstest symlink ${n1} ${n0}
      compareout: "0"

    # expect ELOOP rename ${n0}/test ${n2}
    - name: T1 - expect ELOOP rename [n0]/test [n2]
      command: fstest rename ${n0}/test ${n2}
      compareout: "ELOOP"
      exit: 1

    # expect ELOOP rename ${n1}/test ${n2}
    - name: T1 - expect ELOOP rename [n1]/test [n2]
      command: fstest rename ${n1}/test ${n2}
      compareout: "ELOOP"
      exit: 1

    # expect 0 create ${n2} 0644
    - name: T1 - expect 0 create [n2] 0644
      command: fstest create ${n2} 0644
      compareout: "0"

    # expect ELOOP rename ${n2} ${n0}/test
    - name: T1 - expect ELOOP rename [n2] [n0]/test
      command: fstest rename ${n2} ${n0}/test
      compareout: "ELOOP"
      exit: 1

    # expect ELOOP rename ${n2} ${n1}/test
    - name: T1 - expect ELOOP rename [n2] [n1]/test
      command: fstest rename ${n2} ${n1}/test
      compareout: "ELOOP"
      exit: 1

    # expect 0 unlink ${n0}
    - name: T1 - expect 0 unlink [n0]
      command: fstest unlink ${n0}
      compareout: "0"

    # expect 0 unlink ${n1}
    - name: T1 - expect 0 unlink [n1]
      command: fstest unlink ${n1}
      compareout: "0"

    # expect 0 unlink ${n2}
    - name: T1 - expect 0 unlink [n2]
      command: fstest unlink ${n2}
      compareout: "0"
