---
# Install demo systems

- name: Include default variables
  hosts: all
  tasks:
  - include_vars: vars/irods_version.yml

- name: Prep systems
  hosts: demo
  become: yes
  roles:
    - common-prep
    - ssh-lockdown
    - ufw

- name: Install iRODS
  hosts: irods
  become: yes
  roles:
    - { role: irods3, when: irods_version == 3 }
    - { role: irods4, when: irods_version == 4 }

- name: Install Hadoop
  hosts: hadoop
  become: yes
  roles:
    - hadoop
    - demo-install

- name: Install Syndicate MS
  hosts: syndicate-ms
  become: yes
  roles:
    - syndicate-ms

- name: Install Syndicate
  become: yes
  hosts: demo
  roles:
    - syndicate
